theme: jekyll-theme-minimal
title: 小马哥的技术博客
SEOTitle: 小马哥的技术博客 | You Blog
header-img: img/post-bg-rwd.jpg
email: mercyblitz@gmail.com	
description: "You Blog"
keyword: "小马哥, mercyblitz
url: "https://mercyblitz.github.io"
